# This is the final version of netlify.toml

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

  # Set timeout for all functions to 60 seconds
  [functions."*"]
    timeout = 60

[build]
  environment = { SECRETS_SCAN_OMIT_KEYS = "VITE_CLOUDINARY_UPLOAD_PRESET" }
